services:
  kokoro-ui:
    build: .
    container_name: kokoro-ui
    ports:
      - "8889:80"
    volumes:
      - ./public/orator:/usr/share/nginx/html
      - ./public/orator:/usr/share/nginx/html/orator
    restart: unless-stopped
